---

- name: "Include Zabbix gpg ids"
  include_vars: zabbix.yml

- name: "Set short version name"
  set_fact:
    zabbix_short_version: "{{ zabbix_version | regex_replace('\\.', '') }}"

- name: "Debian | Install gpg key"
  apt_key:
    id: "{{ sign_keys[zabbix_short_version][ansible_distribution_release]['sign_key'] }}"
    url: http://repo.zabbix.com/zabbix-official-repo.key
  when:
    - zabbix_repo == "zabbix"
  become: yes
  tags:
    - zabbix-web
    - init
    - config

- name: "Debian | Installing repository {{ ansible_distribution }}"
  apt_repository:
    repo: "{{ item }} http://repo.zabbix.com/zabbix/{{ zabbix_version }}/{{ ansible_distribution.lower() }}/ {{ ansible_distribution_release }} main"
    state: present
  when: zabbix_repo == "zabbix"
  with_items:
    - deb-src
    - deb
  tags:
    - zabbix-web
    - init
    - config

- name: "Debian | Install php5-{{ zabbix_server_database }}"
  apt:
    pkg: php5-{{ zabbix_server_database }}
    state: present
    update_cache: yes
    cache_valid_time: 3600
  when: >
    ( ansible_distribution == 'Ubuntu' and (ansible_distribution_version is version_compare('16.04', '<')))
    or ( ansible_distribution == 'Debian' and (ansible_distribution_version is version_compare('9.0', '<')) )
  tags:
    - zabbix-web
    - init

- name: "Ubuntu | Install php7-{{ zabbix_server_database }}"
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items: "{{ ubuntu_packages }}"
  when: >
    ( ansible_distribution == 'Ubuntu' and (ansible_distribution_version is version_compare('16.04', '>=')))
    or ( ansible_distribution == 'Debian' and (ansible_distribution_version is version_compare('9.0', '>=')) )
  tags:
    - zabbix-server
    - init

- name: "Debian | Install zabbix-web"
  apt:
    pkg: zabbix-frontend-php
    state: "{{ zabbix_web_package_state }}"
    update_cache: yes
    cache_valid_time: 0
  tags:
    - zabbix-web
    - init
    - config

- name: "Debian | Link graphfont.ttf (workaround ZBX-10467)"
  file:
    src: '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf'
    path: '/usr/share/zabbix/fonts/graphfont.ttf'
    state: link
  tags:
    - zabbix-web
    - init
    - config

- name: "Debian | install apache vhost"
  template:
    src: apache_vhost.conf.j2
    dest: /etc/apache2/sites-available/zabbix.conf
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    mode: 0644
  when: zabbix_vhost
  notify:
    - restart apache
  tags:
    - zabbix-web
    - init
    - config
    - apache

- name: "Debian | enable apache vhost"
  file:
    src: /etc/apache2/sites-available/zabbix.conf
    dest: /etc/apache2/sites-enabled/zabbix.conf
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    state: link
  when: zabbix_vhost
  notify:
    - restart apache
  tags:
    - zabbix-server
    - init
    - config
    - apache
