---
# Tasks specific for RedHat systems

- name: "RedHat | Install basic repo file"
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: "{{ item.gpgcheck }}"
    gpgkey: "{{ item.gpgkey }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ zabbix_repo_yum }}"
  when:
    - zabbix_repo == "zabbix"
  tags:
    - zabbix-web

- name: "RedHat | Install zabbix-web-{{ zabbix_server_database }}"
  yum:
    pkg: zabbix-web-{{ zabbix_server_database }}
    state: "{{ zabbix_web_package_state }}"
  tags:
    - zabbix-web

- name: "RedHat | Install apache vhost"
  template:
    src: apache_vhost.conf.j2
    dest: /etc/httpd/conf.d/zabbix.conf
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    mode: 0644
  when: zabbix_vhost
  notify:
    - restart apache
  tags:
    - zabbix-server
