---
# Tasks specific for RedHat systems

- name: "RedHat | Install basic repo file"
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: "{{ item.gpgcheck }}"
    gpgkey: "{{ item.gpgkey }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ zabbix_repo_yum }}"
  when:
    - zabbix_repo == "zabbix"
  tags:
    - zabbix-web

- name: "RedHat | Install zabbix-web-{{ zabbix_server_database }}"
  yum:
    pkg: zabbix-web-{{ zabbix_server_database }}
    state: "{{ zabbix_web_package_state }}"
  register: zabbix_web_package_install
  until: zabbix_web_package_install is succeeded
  tags:
    - zabbix-web

- include_tasks: apache_RedHat.yml
  vars:
    zabbix_apache_servername: "{{ zabbix_websrv_servername }}"
  when: zabbix_websrv == 'apache'
